fix: lint

diff --git a/scripts/bin/lower b/scripts/bin/lower
--- a/scripts/bin/lower
+++ b/scripts/bin/lower
@@ -1,7 +1,20 @@
 #!/usr/bin/env bash
-if [ "$#" -gt 0 ]; then
-  echo "$@" | tr '[:upper:]' '[:lower:]'
-else
-  tr '[:upper:]' '[:lower:]'
+usage() {
+    printf "lower: usage: lower CONTENT\n" >&2
+}
+
+exit_with_error() {
+    printf "lower: error: %s\n" "$1" >&2
+    usage
+    exit 1
+}
+
+if ! [ -p /dev/stdin ] && ! [ "$#" -gt 0 ]; then
+    exit_with_error "missing CONTENT argument"
 fi
 
+if [ -p /dev/stdin ]; then
+    tr '[:upper:]' '[:lower:]'
+else
+    echo "$@" | tr '[:upper:]' '[:lower:]'
+fi
diff --git a/scripts/bin/upper b/scripts/bin/upper
--- a/scripts/bin/upper
+++ b/scripts/bin/upper
@@ -1,7 +1,20 @@
 #!/usr/bin/env bash
-if [ "$#" -gt 0 ]; then
-  echo "$@" | tr '[:lower:]' '[:upper:]'
-else
-  tr '[:lower:]' '[:upper:]'
+usage() {
+    printf "upper: usage: upper CONTENT\n" >&2
+}
+
+exit_with_error() {
+    printf "upper: error: %s\n" "$1" >&2
+    usage
+    exit 1
+}
+
+if ! [ -p /dev/stdin ] && ! [ "$#" -gt 0 ]; then
+    exit_with_error "missing CONTENT argument"
 fi
 
+if [ -p /dev/stdin ]; then
+    tr '[:lower:]' '[:upper:]'
+else
+    echo "$@" | tr '[:lower:]' '[:upper:]'
+fi
